### ISSUE TITLE
Agenda slot 分隔塊

### ISSUE THREAD

**Issue by hereismglee** [ocftw/civictechfest.org#12]
重覆標示了 e.g. 

4F Joy／4F Joy
4F Elegance／4F Elegance

**Comment by pellaeon** [comment]
原本是拿來標示主題用的，像是這樣：
http://summit.g0v.tw/2016/schedules
Wiring／R0

未來有可能需要用到主題標示嗎？

**Comment by hereismglee** [comment]
不會，基本上議程已不會有太大更動了！
建議色塊的顏它就按其它的slot，依房間別來分。

**Comment by pellaeon** [comment]
@hereismglee 現在這個 issue 應該可以 close 掉了？
