### ISSUE TITLE
所有 logo 露出的大小調整 & 轉 PNG24

### ISSUE THREAD

**Issue by ttcat** [ocftw/civictechfest.org#14]
我先全部出了透明背景的 png
但是並沒有調整大小、邊界

要請山藥找時間全部重新處理一次（而且全部要改成 PNG24 匯出，目前只有部分是）
網站上看起來才會比較一致

比方說整體上 Microsoft 看起來比 WCIT 小
這可能要設定固定高度，然後再看比例

全部要上在 footer 的 logo 
https://drive.google.com/drive/u/1/folders/0B0btxvSLjDAqYmhtSmdVZk1SWDg

**Comment by sanyaoooo** [comment]
改好了，看看還有沒有問題～
