### ISSUE TITLE
index - Main event & Side Event 區塊視覺

### ISSUE THREAD

**Issue by ttcat** [ocftw/civictechfest.org#15]
![unnamed](https://user-images.githubusercontent.com/1935330/27850517-d5751258-6187-11e7-9a03-16830af734cd.jpg)

首先，上方的 Sep 11, 12, 13 跟地點會重疊
且 Sep 太靠左邊

但是因為上方的日期是靠右，所以在不同的活動又會往右移
可能看是不是都鎖定在左邊

![unnamed 1](https://user-images.githubusercontent.com/1935330/27850567-23b9975e-6188-11e7-9b51-5cbb88018a91.jpg)

**Comment by sanyaoooo** [comment]
調整過了（包含RWD） 
再看看o不ok
