### ISSUE TITLE
Agenda 小字的分層

### ISSUE THREAD

**Issue by ttcat** [ocftw/civictechfest.org#23]
現在標題下面的小字
是講者、講者所屬組織，有時候還會掛講者的講題（如下面兩張圖）
可能獎者本身要用粗體來區隔

![2017-07-05 14 20 34](https://user-images.githubusercontent.com/1935330/27851453-512ba8b2-618d-11e7-9278-caf6eef170ae.png)
![2017-07-05 14 21 05](https://user-images.githubusercontent.com/1935330/27851469-67cf21fc-618d-11e7-8510-c54e16d5ba56.png)

**Comment by pellaeon** [comment]
要粗體的部分，在 `app/javascripts/components/Schedule/schedules_by_track.json` 的 speaker 欄位裡面用 `<b>` 包起來就可以了，像這樣 `<b>粗體字元</b>` ，請 @lulukeng 幫忙更新一下。
