### ISSUE TITLE
首頁修正 

### ISSUE THREAD

**Issue by lulukeng** [ocftw/civictechfest.org#3]
1 Keynote Speakers 改成 >>Highlighted Speakers 

2. 下方LOGO，有白底的需要去背，然後Partners , 第一行是mySociety , WCIT, 其他都放第二行

**Comment by pellaeon** [comment]
1. done
2. in progress

**Comment by hereismglee** [comment]
Hightlighted > highlighted 

多了個t唷

**Comment by pellaeon** [comment]
fixed
