### ISSUE TITLE
Google Analytics?

### ISSUE THREAD

**Issue by pellaeon** [ocftw/civictechfest.org#33]

**Comment by ttcat** [comment]
@clkao do we have ocf google analytics?

**Comment by pofeng** [comment]
`<script>

  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-102190863-2', 'auto');
  ga('send', 'pageview');

</script>`

**Comment by pofeng** [comment]
我新建了 google analytics 帳戶 ocf ( UA-102190863 ) 
新建 資源 civictechfest.org ( UA-102190863-2 )
把 資源 ocf.tw ( UA-379894-19 ) 移到 google analytics 帳戶 ocf 下面

權限調整 clkao, ttcat , pellaeon 都可讀寫, 如果沒看到, 再告訴我

**Comment by pellaeon** [comment]
已加上！
