### ISSUE TITLE
Order of speakers on homepage

### ISSUE THREAD

**Issue by Gemmamysoc** [ocftw/civictechfest.org#38]
I know there are more speakers to add to the site, but in the meantime I think the order should be as follows:

1. Stephen King
2. Audrey Tang
3. Erie Meyer
4. Nanjira Sambuli
5. James Powell
6. Mathilde Bras
7. Masashi Crete-Nishihata
8. Rebecca Rumbul
9. Michael Canares
10. Chia-Liang Kao
11. Gemma Humphrys
12. Luke Bacon
13. Khairil Yusof

**Comment by hereismglee** [comment]
is it still in shuffle mode?

**Comment by pellaeon** [comment]
Yes, it's still in shuffle mode, I'm removing it.

**Comment by pellaeon** [comment]
Fixed in f92701cf271c86faf3fc0608cf907c97b2d45207
