### ISSUE TITLE
Mobile width 

### ISSUE THREAD

**Issue by ttcat** [ocftw/civictechfest.org#42]
![img_0042](https://user-images.githubusercontent.com/1935330/27996512-0b13e25e-6516-11e7-8f6e-1ef62f1ab719.PNG)

**Comment by sanyaoooo** [comment]
修好哩!

**Comment by ttcat** [comment]
Iphone safari 打開網站一縮小就有了
sanyaoooo <notifications@github.com>於 2017年7月10日 週一，上午3:47寫道：

**Comment by sanyaoooo** [comment]
我修正了一個屬性
再幫我試試看還有沒有這個狀況 (beta版)
感謝

**Comment by ttcat** [comment]
Done
