### ISSUE TITLE
Text change - Venkatesh Kannaiah's presentation

### ISSUE THREAD

**Issue by Gemmamysoc** [ocftw/civictechfest.org#43]
Please could you change the wording on Venkatesh Kannaiah's presentation from:

"Civic Tech in India and why digital citizen engagement matters
Speaker: Venkatesh Kannaiah,Janaagraha (India)"

To: 

"Impacts of Civic Tech experiments in India: IPaidABribe and IChangeMyCity 
Speaker: Venkatesh Kannaiah, Knight International Journalism Fellow (India)"

**Comment by hereismglee** [comment]
fixed and has pushed to the official site
