### ISSUE TITLE
Missing title in the the abstract of Fireside Chat

### ISSUE THREAD

**Issue by hereismglee** [ocftw/civictechfest.org#44]
Agenda, Day 1 
the abstract of Fireside Chat has no title and time info

這個 abstract 右上角的 "X" 不能關掉 abstract

**Comment by ttcat** [comment]
Can't repeat this bug, maybe fixed?

**Comment by hereismglee** [comment]
右邊 abstract 上方應該要有這個 panel 的 title 跟場地資訊，我在 beta 版上還沒看到

正確的樣子：
<img width="1280" alt="screen shot 2017-07-18 at 4 13 51 pm" src="https://user-images.githubusercontent.com/13115122/28307058-264c5e10-6bd4-11e7-9d14-64f31ccb6649.png">

錯的頁面：
<img width="1280" alt="screen shot 2017-07-18 at 4 13 35 pm" src="https://user-images.githubusercontent.com/13115122/28307037-1287adee-6bd4-11e7-9566-0108a09270d3.png">
