### ISSUE TITLE
Edits to English language on Tickets page

### ISSUE THREAD

**Issue by Gemmamysoc** [ocftw/civictechfest.org#52]
Here are my suggested edits to the text on [this page](http://civictechfest.org/ticket):

1. Change '( alongside WCIT 2017 )' to '(includes entry to WCIT 2017)'

2. Change 'Ticket is required to enter the TICTeC@Taipei.' to 'Tickets are required to enter TICTeC@Taipei

3. Change 'Tickets Included' to 'Tickets include:'

4. Change 'Single room with breakfest of 4 stars hotel for 4 nights during Sep.10th-14th (excpet regurlar ticket without accommodation)' to: 'Single room with breakfast at 4-star hotel for 4 nights from 10th-14th September (except regular tickets without accommodation)'

5. Change 'Free to enter TICTec@Taipei & WCIT 2017 and Social events (RSVP)' to: 'Free entrance to TICTec@Taipei & WCIT 2017, plus social events (RSVP needed)

6. Change 'TICTeC@Taipei will use the same "Badge" and "Venue" with WCIT 2017.' to: 'TICTeC@Taipei will use the same "Badge" and "Venue" as WCIT 2017.'

7. Change 'The "Badge" can be acquired in the WCIT registration desk.' to: 'The "Badge" can be acquired at the WCIT registration desk.'

**Comment by lulukeng** [comment]
Have edited!! 
Wait for transforming from Beta website to official website.
