### ISSUE TITLE
Size of side event logos

### ISSUE THREAD

**Issue by ttcat** [ocftw/civictechfest.org#54]
![2017-07-18 15 41 02](https://user-images.githubusercontent.com/1935330/28305811-b765d016-6bcf-11e7-9782-f6b6e8f6fda4.png)

先前 logo 太大，所以 @lulukeng 好像改小了？但現在又有點太小，可否請山藥幫忙調整

**Comment by ttcat** [comment]
可能要比對一下，下方 speakers 的大頭的圓圈大小比例

**Comment by sanyaoooo** [comment]
done

**Comment by ttcat** [comment]
好像又變太大了 再小 10~20% ?

**Comment by sanyaoooo** [comment]
再調整過了，看看o不ok

**Comment by ttcat** [comment]
電腦版 OK 手機版不行喔

**Comment by sanyaoooo** [comment]
手機版也調整了，再麻煩確認囉

**Comment by ttcat** [comment]
@sanyaoooo 我看到的是上面的 TICTeC 變小了，但是下面的 side event 們還是大的

**Comment by sanyaoooo** [comment]
調了side event在手機板的大小
