### ISSUE TITLE
Moderator 在 speaker list 展開的時候版型和 speaker 長的不一樣

### ISSUE THREAD

**Issue by ttcat** [ocftw/civictechfest.org#60]
純 Moderator，沒自己議程：
http://beta.civictechfest.org/speakers#none-14
（大頭照變整張，且上方的翻譯字樣沒拿掉）

若有講者有兩個以上議程時，應該並列顯示（ @hereismglee 我們有任何一個講者是有超過一個的議程嗎？）

**Comment by hereismglee** [comment]
@ttcat 有喔，第一天的 clkao, Rebecca 有擔任講者 + moderator；Orianne 有第一天跟第三天兩場；Najira 在第一天也有兩場

目前這些人都只顯示了一場

**Comment by ttcat** [comment]
OK 版型再請 @pellaeon @sanyaoooo 調整

Emergency 的是：「Live interpretation are available for both English and Mandarin sessions.」這段要先消失
Thanks

**Comment by ttcat** [comment]
OK 版型再請 @pellaeon @sanyaoooo 調整

Emergency 的是：「Live interpretation are available for both English and Mandarin sessions.」這段要先消失
Thanks

**Comment by pellaeon** [comment]
原本的 issue 無法重現，我先關閉，有問題再開。
