### ISSUE TITLE
Speakers page wording & CSS

### ISSUE THREAD

**Issue by ttcat** [ocftw/civictechfest.org#61]
http://beta.civictechfest.org/speakers

「講者」=> Speakers

大頭照與下方的名字、單位太擠
手機版看變成三個一排顯示，有的人的介紹會被下面的大頭切到
建議改成一排一個或一排兩個，高度變高
或直接拿手頁的 css 來調整

**Comment by sanyaoooo** [comment]
先套了首頁的speaker樣式
再看看有沒有問題～

**Comment by ttcat** [comment]
thanks!
