### ISSUE TITLE
首頁 timeline side event 修正

### ISSUE THREAD

**Issue by ttcat** [ocftw/civictechfest.org#62]
Code for Gender 要改只有 10 號
NGO Data Bootcamp 改 15 號

Toolbox Hackathon 改名稱：Creative Workshop

**Comment by pellaeon** [comment]
@ttcat 可以直接到 app/jsons/side_events.json 編輯 side event

**Comment by ttcat** [comment]
這是上方的那個 timeline 嗎？

**Comment by pellaeon** [comment]
不是，json只變更下方的個別顯示。
timeline部分我修好了，請檢查後 close。

**Comment by ttcat** [comment]
請問有 push 了嗎？正式主機上看還是錯的
