### ISSUE TITLE
agenda 無 "speaker" , "speaker_f" 展開視窗會當掉

### ISSUE THREAD

**Issue by hereismglee** [ocftw/civictechfest.org#70]
workshop 如果沒有設定 "speaker" , "speaker_f" 
右邊展開的視窗會當掉。

但目前workshop 都不會有單獨的講者簡介 & bio 

(請忽略我最後兩次錯的 commit @@)

<img width="1280" alt="screen shot 2017-08-09 at 10 11 38 am" src="https://user-images.githubusercontent.com/13115122/29102733-bf2a8574-7ced-11e7-9aef-97c21c341d15.png">

**Comment by pellaeon** [comment]
請直接在那個 event 加上空的 speaker, speaker_f 欄位，像這樣：
```
"speaker": "",
"speaker_f": "",
```
