### ISSUE TITLE
Footer 要新增logo 

### ISSUE THREAD

**Issue by rockerafi** [ocftw/civictechfest.org#72]
1. 要把 WAGL 的 Logo 移到 promoting partner
2. 要加入 Wiki Taiwan 和 Open street map Taiwan 的 logo 到 partner ( 以放入雲端partner 資料夾 )

**Comment by sanyaoooo** [comment]
更新上去囉

**Comment by rockerafi** [comment]
@pellaeon 麻煩修一下，現在看不到

**Comment by pellaeon** [comment]
已經看得到了
