### ISSUE TITLE
Agenda 展開頁面，有些大頭照會壓到線，有的不會，不知道為什麼

### ISSUE THREAD

**Issue by ttcat** [ocftw/civictechfest.org#76]
http://beta.civictechfest.org/agenda#day1-all-10

http://beta.civictechfest.org/agenda#day2-all-2

http://beta.civictechfest.org/agenda#day2-all-12 （Title 太長要自動斷行）

http://beta.civictechfest.org/agenda#day2-all-13

http://beta.civictechfest.org/agenda#day2-all-17

http://beta.civictechfest.org/agenda#day3-all-7

**Comment by sanyaoooo** [comment]
OK 修好了
