### ISSUE TITLE
首頁右側的資訊連結

### ISSUE THREAD

**Issue by hereismglee** [ocftw/civictechfest.org#77]
請幫忙開首頁右側的資訊連結
只要放 unconference, shared note, social feeds, media contact,

<img width="1280" alt="screen shot 2017-08-17 at 5 25 00 pm" src="https://user-images.githubusercontent.com/13115122/29405752-6c9e8f6e-8371-11e7-8e93-7b6e3087522b.png">

**Comment by pellaeon** [comment]
note:
看看能不能先用 get param 隱藏/開啟，預設隱藏，這樣方便測試
