### ISSUE TITLE
footer 要加一些partners

### ISSUE THREAD

**Issue by rockerafi** [ocftw/civictechfest.org#79]
1. code for gender 要改成橫的logo
2. 要加 womany 的logo
3. 要加開拓文教基金會的 Logo
4. 要加資料科學協會 的logo
5. 要加民主基金會的 logo 

以上logo 都在雲端 CTF 視覺 > partners 那個資料夾 
感謝山藥！

**Comment by sanyaoooo** [comment]
OK 改好囉
順便加上滑鼠滑入的效果
