### ISSUE TITLE
新增兩個贊助商

### ISSUE THREAD

**Issue by ttcat** [ocftw/civictechfest.org#83]
LOGO 在 https://drive.google.com/drive/u/1/folders/0B8ZDAvRh9yhpcXYwTkVxWDVCWDA

KKBOX 的 guideline https://www.kkbox.com/about/zh-tw/about/logo
都在 MS 後面

手冊跟其他輸出物也麻煩補上這兩個
感謝！

**Comment by sanyaoooo** [comment]
網站加上了 （beta）
