### ISSUE TITLE
沒 ttcat speaker 的內容 ...

### ISSUE THREAD

**Issue by ttcat** [ocftw/civictechfest.org#85]
http://civictechfest.org/speakers#Wu_Min_Hsuan_(ttcat)

**Comment by hereismglee** [comment]
但是code裡有，你在這頁裡也有耶
我也不知道為什麼
http://civictechfest.org/agenda#day3-all-7

**Comment by pellaeon** [comment]
原始的設計裡面，講者名稱包含括號的話會出問題。

**Comment by pellaeon** [comment]
如果要支援括號的話，網址會變很醜，類似這樣：
`http://civictechfest.org/speakers#YXNpb2R1byBhczhkNyBvSUFTRFVGIE9JIG9pdWRzZ2YK`

**Comment by pellaeon** [comment]
Fixed in fb1d36bf1bb1ae6e0fae602936c7a8e1bbad506b
